// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hangar-welcome/BoardingPass.tsx": () => import("../components/mockups/hangar-welcome/BoardingPass.tsx"),
  "./components/mockups/hangar-welcome/ImmersiveHero.tsx": () => import("../components/mockups/hangar-welcome/ImmersiveHero.tsx"),
  "./components/mockups/hangar-welcome/MissionBriefing.tsx": () => import("../components/mockups/hangar-welcome/MissionBriefing.tsx"),
  "./components/mockups/hangar-welcome/TacticalTerminal.tsx": () => import("../components/mockups/hangar-welcome/TacticalTerminal.tsx")
};
